name: "Fetch PR Labels"
description: "Fetches all labels from a PR and returns them"

inputs:
  github_token:
    description: "GitHub token for API access"
    required: true

outputs:
  labels:
    description: "Comma-separated list of all PR labels"
    value: ${{ steps.fetch.outputs.labels }}
  label_count:
    description: "Number of labels on the PR"
    value: ${{ steps.fetch.outputs.label_count }}

runs:
  using: "composite"
  steps:
    - name: Fetch PR Labels
      id: fetch
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { owner, repo } = context.repo;
          let prNumber;

          if (context.payload.pull_request) {
            prNumber = context.payload.pull_request.number;
            console.log(`Detected PR event: #${prNumber}`);
          } else if (context.payload.head_commit) {
            const commitSha = context.payload.head_commit.id;
            console.log(`Finding PR for commit: ${commitSha}`);
            try {
              const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner,
                repo,
                commit_sha: commitSha,
              });
              if (prs.length > 0) {
                prNumber = prs[0].number;
                console.log(`Found PR #${prNumber} for commit.`);
              } else {
                console.log("No PR found for this commit. Skipping label fetch.");
                core.setOutput('labels', '');
                core.setOutput('label_count', '0');
                return;
              }
            } catch (error) {
              console.log(`Error fetching PR: ${error.message}`);
              core.setOutput('labels', '');
              core.setOutput('label_count', '0');
              return;
            }
          } else {
            console.log("No PR or commit context found.");
            core.setOutput('labels', '');
            core.setOutput('label_count', '0');
            return;
          }

          const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
          const labels = (prData.labels || []).map(l => l.name);
          const labelCount = labels.length;
          console.log(`Found ${labelCount} label(s): ${labels.join(', ') || 'none'}`);

          core.setOutput('labels', labels.join(','));
          core.setOutput('label_count', labelCount.toString());