name: "Fetch PR Labels"
description: "Fetches all labels from a PR and returns them"

outputs:
  labels:
    description: "Comma-separated list of all PR labels"
    value: ${{ steps.fetch.outputs.labels }}

runs:
  using: "composite"
  steps:
    - name: Fetch PR Labels
      id: fetch
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        github-token: ${{ github.token }}
        script: |
          const { owner, repo } = context.repo;
          
          if (!context.payload.pull_request) {
            console.log("No PR context found. Exiting.");
            core.setOutput('labels', '');
            return;
          }
          
          const prNumber = context.payload.pull_request.number;
          console.log(`Detected PR event: #${prNumber}`);
          
          try {
            const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: prNumber });
            const labels = (prData.labels || []).map(l => l.name);
            console.log(`Found ${labels.length} label(s): ${labels.join(', ') || 'none'}`);
            core.setOutput('labels', labels.join(','));
          } catch (error) {
            console.error(`Error fetching PR labels: ${error.message}`);
            core.setOutput('labels', '');
          }