name: "Validate Release Note Label"
description: "Ensures PR has either add_release_note or skip_release_note label"

runs:
  using: "composite"
  steps:
    - name: Fetch PR Labels
      id: fetch-labels
      uses: ./.github/actions/common/fetch-pr-label
      with:
        github_token: ${{ github.token }}

    - name: Validate Required Labels
      uses: actions/github-script@60a0d83039c74a4a4e2d7c7fba9a0bba3e3d5b7d3 # v7.0.1 pinned commit
      with:
        github-token: ${{ github.token }}
        script: |
          const labels = ('${{ steps.fetch-labels.outputs.labels }}' || '')
            .split(',')
            .map(l => l.trim())
            .filter(Boolean);

          console.log(`PR labels: ${labels.join(', ') || 'none'}`);

          const hasAdd = labels.includes('add_release_note');
          const hasSkip = labels.includes('skip_release_note');

          if (hasAdd && hasSkip) {
            core.setFailed("❌ Both 'add_release_note' and 'skip_release_note' labels are present. Only one is allowed.");
          } else if (!hasAdd && !hasSkip) {
            core.setFailed("❌ Missing required label. Add one of: 'add_release_note' or 'skip_release_note'.");
          } else if (hasAdd) {
            console.log("✅ 'add_release_note' found — release notes expected.");
          } else {
            console.log("⏩ 'skip_release_note' found — release notes will be skipped.");
          }