name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (Java Development Kit)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Cache Maven dependencies to speed up the build
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven clean and test
      - name: Run Maven clean test
        run: mvn clean test